version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: "/myapp/docker-credentials/username"
    DOCKER_REGISTRY_PASSWORD: "/myapp/docker-credentials/password"
    DOCKER_REGISTRY_URL: "/myapp/docker-registry/url"

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r day-14/simple-python-app/requirements.txt
      # Defining the image name variable here so the build command works
      - imagename="simple-python-flask-app"
  build:
    commands:
      - echo "Running tests..."
      - cd day-14/simple-python-app/
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - echo "Building the Docker image..."
      - docker build -t $imagename .
      - echo "Tagging and Pushing the Docker image..."
      - docker tag $imagename:latest $DOCKER_REGISTRY_USERNAME/$imagename:latest
      - docker push $DOCKER_REGISTRY_USERNAME/$imagename:latest
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '*/'
  base-directory: 'day-14/simple-python-app'
